---
- name: Install and configure nginx
  hosts: nginx
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=installed
      sudo: yes

    - name: Copy keys
      copy: src="nginx/files/{{item}}" dest="/etc/nginx/{{item}}"
      with_items: [ cert.crt, cert.key ]
      sudo: yes

    - name: Copy config
      template: src=nginx/templates/default dest=/etc/nginx/sites-available/default
      sudo: yes
      notify:
       - Restart nginx

    - name: Create symlink
      file: src=/etc/nginx/sites-available/default
            dest=/etc/nginx/sites-enabled/default
            state=link
            force=yes
      sudo: yes

    - name: Copy nginx upstart file
      copy: src=nginx/files/nginx.conf dest=/etc/init/nginx.conf
      sudo: yes

  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted
      sudo: yes